package render_test

import (
	"strings"
	"testing"

	"github.com/Vikasa2M/vikasa-infra/internal/accounts"
	"github.com/Vikasa2M/vikasa-infra/internal/render"
	"github.com/Vikasa2M/vikasa-infra/internal/topology"
)

func TestAccountsRenderer_ExdotShared(t *testing.T) {
	root, err := topology.Load("../../examples/exdot-shared.json")
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	m, err := accounts.Build(root)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	files, err := render.AccountsRenderer{}.Render(m)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	conf := string(files["accounts.conf"])

	for _, want := range []string{
		"accounts {",
		"CENTRAL {",
		"DISTRICT_D7 {",
		"SYSTEM {",
		"jetstream: enabled",
		`{ stream: "vikasa.exdot.d7.>" }`,
		`{ stream: { account: DISTRICT_D7, subject: "vikasa.exdot.d7.>" } }`,
		`publish   { allow: ["vikasa.exdot.d7.>"] }`,
		`subscribe { allow: ["vikasa.exdot.d7.>"] }`,
		"system_account: SYSTEM",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("accounts.conf missing %q\n%s", want, conf)
		}
	}
	if !strings.HasPrefix(conf, "# AUTOGENERATED") {
		t.Errorf("accounts.conf missing autogen banner")
	}

	checkGolden(t, "accounts.conf", files["accounts.conf"])
}

func TestAccountsRenderer_DMZPublishDeny(t *testing.T) {
	m := &accounts.Model{DOT: "exdot", Accounts: []accounts.Account{
		{
			Name:      "DMZ",
			JetStream: true,
			Users: []accounts.UserTemplate{{
				Label:       "research",
				Subscribe:   []string{"vikasa.exdot.share.research.>"},
				PublishDeny: []string{">"},
			}},
		},
	}}
	files, err := render.AccountsRenderer{}.Render(m)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	conf := string(files["accounts.conf"])
	for _, want := range []string{
		`subscribe { allow: ["vikasa.exdot.share.research.>"] }`,
		`publish   { deny: [">"] }`,
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("accounts.conf missing %q\n%s", want, conf)
		}
	}
	if strings.Contains(conf, `publish   { allow`) {
		t.Errorf("DMZ user must not gain a publish allow\n%s", conf)
	}
}
