package render

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
	"text/template"
	"time"

	"github.com/Vikasa2M/vikasa-infra/internal/plan"
)

// BareMetalRenderer materializes a bare-metal cluster's slice into:
//   - nats-<host>.conf      one per host (topology-only server config)
//   - nats-server.service   a systemd unit (host-agnostic)
//   - streams/<NAME>.json   one per stream ("nats stream add --config" input)
//
// Security (TLS/accounts/operator) is owned by sub-project B and pulled in via
// the `include "security.conf"` directive in each nats.conf.
type BareMetalRenderer struct{}

var natsConfTmpl = template.Must(template.New("natsconf").Parse(
	`# AUTOGENERATED by vikasa-infra/cmd/gen — topology + TLS listener config.
# Accounts and operator/resolver config are owned by sub-project B and supplied
# via the included security.conf below. The TLS cert files referenced here
# (/etc/vikasa/tls/*.pem) are operator-provisioned (e.g. vault-agent).

server_name: {{ .ServerName }}
port: 4222
http_port: 8222

tls {
  cert_file: /etc/vikasa/tls/client-cert.pem
  key_file:  /etc/vikasa/tls/client-key.pem
  ca_file:   /etc/vikasa/tls/ca.pem
  verify: true
  timeout: 3
}

cluster {
  name: {{ .ClusterName }}
  port: 6222
  routes = [
{{- range .Routes }}
    {{ . }}
{{- end }}
  ]
  tls {
    cert_file: /etc/vikasa/tls/cluster-cert.pem
    key_file:  /etc/vikasa/tls/cluster-key.pem
    ca_file:   /etc/vikasa/tls/ca.pem
    verify: true
    timeout: 3
  }
}

leafnodes {
  port: 7422
  tls {
    cert_file: /etc/vikasa/tls/leafnode-server-cert.pem
    key_file:  /etc/vikasa/tls/leafnode-server-key.pem
    ca_file:   /etc/vikasa/tls/ca.pem
    verify: true
    timeout: 3
  }
{{- if not .IsCentral }}
  remotes = [
    {
      urls: ["{{ .CentralLeafURL }}"]
      tls {
        cert_file: /etc/vikasa/tls/leafnode-server-cert.pem
        key_file:  /etc/vikasa/tls/leafnode-server-key.pem
        ca_file:   /etc/vikasa/tls/ca.pem
        timeout: 3
      }
    }
  ]
{{- end }}
}

jetstream {
  domain: {{ .JSDomain }}
  store_dir: /var/lib/nats/jetstream
  max_memory_store: 1GB
  max_file_store: 100GB
}

# Supplied by sub-project B (PKI / accounts). See the deployment runbook.
include "security.conf"
`))

type natsConfData struct {
	ServerName     string
	ClusterName    string
	JSDomain       string
	Routes         []string
	IsCentral      bool
	CentralLeafURL string
}

// natsServiceUnit is the systemd unit (host-agnostic; each host installs its
// own nats-<host>.conf as /etc/vikasa/nats.conf).
const natsServiceUnit = `# AUTOGENERATED by vikasa-infra/cmd/gen
[Unit]
Description=Vikasa NATS server (JetStream + leaf)
Documentation=https://github.com/Vikasa2M/vikasa-infra
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=nats
Group=nats
ExecStart=/usr/local/bin/nats-server -c /etc/vikasa/nats.conf
Restart=on-failure
RestartSec=5
StateDirectory=nats
StateDirectoryMode=0750
ReadWritePaths=/var/lib/nats
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
`

// bareStreamConfig is the subset of the NATS StreamConfig JSON that
// `nats stream add --config <file>` consumes. Field order is fixed for
// deterministic output. max_age is in nanoseconds (NATS Duration encoding).
type bareStreamConfig struct {
	Name        string             `json:"name"`
	Retention   string             `json:"retention"`
	Storage     string             `json:"storage"`
	NumReplicas int                `json:"num_replicas"`
	MaxAge      int64              `json:"max_age,omitempty"`
	MaxBytes    int64              `json:"max_bytes,omitempty"`
	Duplicates  int64              `json:"duplicates,omitempty"`
	RePublish   *bareRePublish     `json:"republish,omitempty"`
	Sources     []bareStreamSource `json:"sources,omitempty"`
}

// bareRePublish mirrors the NATS StreamConfig republish block (src/dest).
type bareRePublish struct {
	Src  string `json:"src"`
	Dest string `json:"dest"`
}

type bareStreamSource struct {
	Name              string                 `json:"name"`
	External          *bareStreamExternal    `json:"external,omitempty"`
	FilterSubject     string                 `json:"filter_subject,omitempty"`
	SubjectTransforms []bareSubjectTransform `json:"subject_transforms,omitempty"`
}

// bareSubjectTransform mirrors the JSON shape of a per-source subject
// transform in the NATS StreamConfig (jsm SubjectTransformConfig).
type bareSubjectTransform struct {
	Src  string `json:"src"`
	Dest string `json:"dest"`
}

type bareStreamExternal struct {
	API string `json:"api"`
}

// RenderCluster implements SubstrateRenderer.
func (BareMetalRenderer) RenderCluster(c ClusterSlice) (map[string][]byte, error) {
	if len(c.Hosts) == 0 {
		return nil, fmt.Errorf("baremetal render: cluster %q has no hosts", c.ID)
	}
	out := map[string][]byte{}

	for i, host := range c.Hosts {
		var routes []string
		for j, h := range c.Hosts {
			if j == i {
				continue
			}
			routes = append(routes, "nats://"+h+":6222")
		}
		data := natsConfData{
			ServerName:     fmt.Sprintf("%s-%d", c.ID, i+1),
			ClusterName:    c.ID,
			JSDomain:       c.JSDomain,
			Routes:         routes,
			IsCentral:      c.IsCentral,
			CentralLeafURL: centralLeafURL(c),
		}
		var buf bytes.Buffer
		if err := natsConfTmpl.Execute(&buf, data); err != nil {
			return nil, fmt.Errorf("baremetal render: %s nats.conf: %w", host, err)
		}
		out["nats-"+sanitizeHostFilename(host)+".conf"] = buf.Bytes()
	}

	out["nats-server.service"] = []byte(natsServiceUnit)

	for _, s := range c.Streams {
		j, err := renderBareStreamConfig(s)
		if err != nil {
			return nil, err
		}
		out["streams/"+s.Name+".json"] = j
	}

	return out, nil
}

func renderBareStreamConfig(s plan.Stream) ([]byte, error) {
	cfg := bareStreamConfig{
		Name:        s.Name,
		Retention:   "limits",
		Storage:     "file",
		NumReplicas: s.Replicas,
	}
	if s.MaxAge != "" {
		d, err := time.ParseDuration(s.MaxAge)
		if err != nil {
			return nil, fmt.Errorf("baremetal render: stream %s: bad max age %q: %w", s.Name, s.MaxAge, err)
		}
		cfg.MaxAge = d.Nanoseconds()
	}
	cfg.MaxBytes = s.MaxBytes
	if s.Duplicates != "" {
		d, err := time.ParseDuration(s.Duplicates)
		if err != nil {
			return nil, fmt.Errorf("baremetal render: stream %s: bad duplicates window %q: %w", s.Name, s.Duplicates, err)
		}
		cfg.Duplicates = d.Nanoseconds()
	}
	if s.RePublishSource != "" {
		cfg.RePublish = &bareRePublish{Src: s.RePublishSource, Dest: s.RePublishDest}
	}
	for _, src := range s.Sources {
		bs := bareStreamSource{
			Name:     src.Name,
			External: &bareStreamExternal{API: "$JS." + src.Domain + ".API"},
		}
		// A source with a transform remaps instead of filtering; the two are
		// mutually exclusive (same rule as the kubernetes Stream CR path).
		if src.TransformSource != "" {
			bs.SubjectTransforms = []bareSubjectTransform{{Src: src.TransformSource, Dest: src.TransformDest}}
		} else {
			bs.FilterSubject = src.FilterSubject
		}
		cfg.Sources = append(cfg.Sources, bs)
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("baremetal render: stream %s: %w", s.Name, err)
	}
	return append(b, '\n'), nil
}

// sanitizeHostFilename makes a hostname safe to use as a filename component.
func sanitizeHostFilename(h string) string {
	r := strings.NewReplacer("/", "-", ":", "-")
	return r.Replace(h)
}

// centralLeafURL is the tls:// URL a regional cluster dials to leaf up to
// central (the leaf remote is mTLS). Empty for the central cluster itself
// (which has no upstream).
func centralLeafURL(c ClusterSlice) string {
	if c.IsCentral || c.CentralLeafEndpoint == "" {
		return ""
	}
	return "tls://" + c.CentralLeafEndpoint
}
