package render_test

import (
	"strings"
	"testing"

	"github.com/Vikasa2M/vikasa-infra/internal/render"
)

func TestDNSRenderer_ExdotShared(t *testing.T) {
	p := loadPlan(t, "../../examples/exdot-shared.json")

	files, err := render.DNSRenderer{}.Render(p)
	if err != nil {
		t.Fatalf("DNSRenderer.Render: %v", err)
	}

	dnsYAML, ok := files["leaf-dns.yaml"]
	if !ok {
		t.Fatal("leaf-dns.yaml not found in output")
	}
	dnsStr := string(dnsYAML)

	// Banner present.
	if !strings.HasPrefix(dnsStr, "# AUTOGENERATED") {
		t.Errorf("leaf-dns.yaml: missing autogen banner")
	}

	// Exactly 2 DNS records.
	recordCount := strings.Count(dnsStr, "  - name:")
	if recordCount != 2 {
		t.Errorf("leaf-dns.yaml: expected 2 records, got %d\ncontent:\n%s", recordCount, dnsStr)
	}

	// Check expected names and targets.
	wantRecords := []struct{ name, target string }{
		{"leaf-exdot-d7-0.nats.vikasa.exdot", "leaf-d7a.nats.vikasa.exdot:7422"},
		{"leaf-exdot-d7-8.nats.vikasa.exdot", "leaf-d7b.nats.vikasa.exdot:7422"},
	}
	for _, want := range wantRecords {
		if !strings.Contains(dnsStr, "name: "+want.name) {
			t.Errorf("leaf-dns.yaml: missing DNS name %q\ncontent:\n%s", want.name, dnsStr)
		}
		if !strings.Contains(dnsStr, "target: "+want.target) {
			t.Errorf("leaf-dns.yaml: missing DNS target %q\ncontent:\n%s", want.target, dnsStr)
		}
	}

	// Golden comparison.
	checkGolden(t, "leaf-dns.yaml", dnsYAML)
}
