package render

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// chartTmpl renders a per-cluster Chart.yaml (Helm v2 application chart). The
// chart version is intentionally pinned (not derived from git/topology); bump it
// manually on a breaking chart-schema change.
var chartTmpl = template.Must(template.New("chart").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: v2
name: vikasa-{{ .ID }}
description: Vikasa NATS substrate for cluster {{ .ID }}
type: application
version: 0.1.0
appVersion: "1.0.0"
`))

// valuesTmpl renders values.yaml whose defaults reproduce the kustomize-mode
// concrete knob values (so a no-values `helm template` matches the default output).
var valuesTmpl = template.Must(template.New("values").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
namespace: {{ .Namespace }}
tlsIssuer: {{ .TLSIssuer }}
secretStore: {{ .SecretStore }}
prometheusRelease: {{ .PrometheusRelease }}
`))

// Helm value references substituted into the chart templates. The sentinels are
// brace-free so they survive helmEscapeBraces (which neutralizes every other
// {{ }} in the rendered manifests, e.g. the literal Prometheus $labels
// expressions in the credhealth rule).
const (
	snNamespace = "\x00VIKASA_HELM_NAMESPACE\x00"
	snIssuer    = "\x00VIKASA_HELM_ISSUER\x00"
	snStore     = "\x00VIKASA_HELM_STORE\x00"
	snRelease   = "\x00VIKASA_HELM_RELEASE\x00"
)

// helmEscapeBraces rewrites every literal {{ and }} so Helm reproduces them
// verbatim instead of parsing them as actions. Applied to rendered manifests
// before the knob sentinels (which contain no braces) are swapped for live
// {{ .Values.x }} references.
func helmEscapeBraces(b []byte) string {
	s := string(b)
	// Two-phase swap via NUL placeholders avoids re-processing inserted braces.
	s = strings.ReplaceAll(s, "{{", "\x00O\x00")
	s = strings.ReplaceAll(s, "}}", "\x00C\x00")
	s = strings.ReplaceAll(s, "\x00O\x00", `{{ "{{" }}`)
	s = strings.ReplaceAll(s, "\x00C\x00", `{{ "}}" }}`)
	return s
}

// renderHelmChart packages one kubernetes cluster's slice as a Helm chart. It
// reuses K8sRenderer by injecting sentinel tokens for the four deployment knobs,
// escapes all pre-existing {{ }} in the rendered manifests (so Helm emits them
// literally), then substitutes the sentinels back to live {{ .Values.x }}
// references. This ensures the ONLY live Helm actions in the output are our
// four knob references; every pre-existing {{ }} (e.g. Prometheus $labels
// expressions in credhealth) becomes literal output.
// Returns chart-root-relative files (Chart.yaml, values.yaml,
// templates/<resource>.yaml). kustomization.yaml is dropped (Helm does not use
// it). Caller prefixes these under charts/<id>/.
func renderHelmChart(slice ClusterSlice) (map[string][]byte, error) {
	// Capture the real knob values for values.yaml defaults BEFORE overriding.
	defaults := struct {
		Namespace, TLSIssuer, SecretStore, PrometheusRelease string
	}{
		Namespace:         slice.Namespace,
		TLSIssuer:         slice.IssuerName,
		SecretStore:       slice.SecretStore,
		PrometheusRelease: slice.PrometheusRelease,
	}

	// Override the four knobs with brace-free sentinel tokens. K8sRenderer emits
	// these sentinels verbatim wherever the concrete value would appear. They
	// survive helmEscapeBraces unchanged, then get replaced with live Helm actions.
	chartSlice := slice
	chartSlice.Namespace = snNamespace
	chartSlice.IssuerName = snIssuer
	chartSlice.SecretStore = snStore
	chartSlice.PrometheusRelease = snRelease

	rendered, err := K8sRenderer{}.RenderCluster(chartSlice)
	if err != nil {
		return nil, fmt.Errorf("helm chart %s: %w", slice.ID, err)
	}

	out := map[string][]byte{}
	for name, content := range rendered {
		if name == "kustomization.yaml" {
			continue // Helm ignores kustomization; not part of the chart
		}
		s := helmEscapeBraces(content)
		s = strings.ReplaceAll(s, snNamespace, "{{ .Values.namespace }}")
		s = strings.ReplaceAll(s, snIssuer, "{{ .Values.tlsIssuer }}")
		s = strings.ReplaceAll(s, snStore, "{{ .Values.secretStore }}")
		s = strings.ReplaceAll(s, snRelease, "{{ .Values.prometheusRelease }}")
		out["templates/"+name] = []byte(s)
	}

	var chartBuf bytes.Buffer
	if err := chartTmpl.Execute(&chartBuf, slice); err != nil {
		return nil, fmt.Errorf("helm chart %s: Chart.yaml: %w", slice.ID, err)
	}
	out["Chart.yaml"] = chartBuf.Bytes()

	var valsBuf bytes.Buffer
	if err := valuesTmpl.Execute(&valsBuf, defaults); err != nil {
		return nil, fmt.Errorf("helm chart %s: values.yaml: %w", slice.ID, err)
	}
	out["values.yaml"] = valsBuf.Bytes()

	return out, nil
}
