package render

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/Vikasa2M/vikasa-infra/internal/credhealth"
	"github.com/Vikasa2M/vikasa-infra/internal/plan"
)

const banner = "# AUTOGENERATED by vikasa-infra/cmd/gen\n"

// streamCRTmpl is the text/template for a single NACK Stream CR.
// Conditional fields (maxAge, sources, filterSubject, subjectTransforms) are
// omitted when empty. A source with TransformSource emits a subjectTransforms
// block instead of filterSubject; the two are mutually exclusive.
var streamCRTmpl = template.Must(template.New("streamCR").Parse(`apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: {{ .MetaName }}
  labels:
    vikasa.dot: {{ .DOT }}
    vikasa.tier: {{ .Tier }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Wave }}"
spec:
  name: {{ .Name }}
  replicas: {{ .Replicas }}
  storage: file
  retention: limits
{{- if .MaxAge }}
  maxAge: {{ .MaxAge }}
{{- end }}
{{- if .MaxBytes }}
  maxBytes: {{ .MaxBytes }}
{{- end }}
{{- if .Duplicates }}
  duplicateWindow: {{ .Duplicates }}
{{- end }}
{{- if .RePublishSource }}
  republish:
    source: {{ .RePublishSource }}
    destination: {{ .RePublishDest }}
{{- end }}
{{- if .Sources }}
  sources:
{{- range .Sources }}
  - name: {{ .Name }}
    externalApiPrefix: $JS.{{ .Domain }}.API
{{- if .TransformSource }}
    subjectTransforms:
    - source: {{ .TransformSource }}
      dest: {{ .TransformDest }}
{{- else if .FilterSubject }}
    filterSubject: {{ .FilterSubject }}
{{- end }}
{{- end }}
{{- end }}
`))

// streamCRData is the template data for a single Stream CR.
type streamCRData struct {
	MetaName        string
	DOT             string
	Tier            string
	Wave            int
	Name            string
	Replicas        int
	Storage         string
	Retention       string
	MaxAge          string
	MaxBytes        int64
	Duplicates      string
	RePublishSource string
	RePublishDest   string
	Sources         []sourceData
}

type sourceData struct {
	Name            string
	Domain          string
	FilterSubject   string
	TransformSource string
	TransformDest   string
}

// toMetaName converts a NATS stream name (UPPER_SNAKE) to lower-kebab for k8s metadata.name.
func toMetaName(s string) string {
	return strings.ToLower(strings.ReplaceAll(s, "_", "-"))
}

// renderStreamCR renders a single Stream CR document (no leading "---").
func renderStreamCR(s plan.Stream, dot string) ([]byte, error) {
	var srcs []sourceData
	for _, src := range s.Sources {
		srcs = append(srcs, sourceData{
			Name:            src.Name,
			Domain:          src.Domain,
			FilterSubject:   src.FilterSubject,
			TransformSource: src.TransformSource,
			TransformDest:   src.TransformDest,
		})
	}

	data := streamCRData{
		MetaName:        toMetaName(s.Name),
		DOT:             dot,
		Tier:            string(s.Tier),
		Wave:            s.Tier.Wave(),
		Name:            s.Name,
		Replicas:        s.Replicas,
		MaxAge:          s.MaxAge,
		MaxBytes:        s.MaxBytes,
		Duplicates:      s.Duplicates,
		RePublishSource: s.RePublishSource,
		RePublishDest:   s.RePublishDest,
		Sources:         srcs,
	}

	var buf bytes.Buffer
	if err := streamCRTmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("k8s render: stream %s: %w", s.Name, err)
	}
	return buf.Bytes(), nil
}

// certTmpl renders a cert-manager Certificate requesting the NATS server's TLS cert.
var certTmpl = template.Must(template.New("cert").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Name }}
  labels:
    vikasa.dot: {{ .DOT }}
    vikasa.cluster: {{ .Cluster }}
spec:
  secretName: {{ .SecretName }}
  issuerRef:
    name: {{ .Issuer }}
    kind: ClusterIssuer
  duration: 2160h0m0s
  renewBefore: 1080h0m0s
  commonName: {{ .CommonName }}
  usages:
    - server auth
  dnsNames:
{{- range .DNSNames }}
    - {{ . }}
{{- end }}
`))

type certData struct {
	Name       string
	DOT        string
	Cluster    string
	SecretName string
	Issuer     string
	CommonName string
	DNSNames   []string
}

// externalSecretTmpl renders an External Secrets ExternalSecret that materializes
// the Infrahub inventory token Secret from an operator-provisioned
// ClusterSecretStore. It contains only a reference (store name + backend key
// path), never a secret value.
var externalSecretTmpl = template.Must(template.New("externalsecret").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infrahub-token
  labels:
    vikasa.dot: {{ .DOT }}
    vikasa.cluster: {{ .Cluster }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .SecretStore }}
    kind: ClusterSecretStore
  target:
    name: infrahub-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .RemoteKey }}
`))

type externalSecretData struct {
	DOT         string
	Cluster     string
	SecretStore string
	RemoteKey   string
}

// serviceMonitorTmpl scrapes the NATS service's prometheus-exporter metrics port.
var serviceMonitorTmpl = template.Must(template.New("servicemonitor").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vikasa-nats-{{ .Cluster }}
  namespace: {{ .Namespace }}
  labels:
    vikasa.dot: {{ .DOT }}
    vikasa.cluster: {{ .Cluster }}
    release: {{ .Release }}
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
`))

type serviceMonitorData struct {
	DOT       string
	Cluster   string
	Namespace string
	Release   string
}

// prometheusRuleTmpl ships a starter set of NATS/JetStream alerts (operators tune
// the exprs to their exporter version). The regional leaf alert is omitted on the
// central cluster. The JetStream* alerts use the exporter's JSZ collector
// (gnatsd_jsz_* metrics, which require the exporter's -jsz flag); like the varz
// exprs they are starters — verify the metric names against your exporter version.
var prometheusRuleTmpl = template.Must(template.New("prometheusrule").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vikasa-nats-{{ .Cluster }}
  namespace: {{ .Namespace }}
  labels:
    vikasa.dot: {{ .DOT }}
    vikasa.cluster: {{ .Cluster }}
    release: {{ .Release }}
spec:
  groups:
    - name: vikasa-nats-{{ .Cluster }}
      rules:
        - alert: NatsServerDown
          expr: up{job="nats", namespace="{{ .Namespace }}"} == 0
          for: 5m
          labels:
            severity: critical
            vikasa_cluster: {{ .Cluster }}
          annotations:
            summary: "NATS server down in cluster {{ .Cluster }}"
        - alert: NatsSlowConsumers
          expr: gnatsd_varz_slow_consumers{namespace="{{ .Namespace }}"} > 0
          for: 10m
          labels:
            severity: warning
            vikasa_cluster: {{ .Cluster }}
          annotations:
            summary: "NATS slow consumers in cluster {{ .Cluster }}"
        - alert: JetStreamStorageHigh
          expr: gnatsd_jsz_max_storage{namespace="{{ .Namespace }}"} > 0 and gnatsd_jsz_storage{namespace="{{ .Namespace }}"} / gnatsd_jsz_max_storage{namespace="{{ .Namespace }}"} > 0.8
          for: 10m
          labels:
            severity: critical
            vikasa_cluster: {{ .Cluster }}
          annotations:
            summary: "JetStream store >80% of max in cluster {{ .Cluster }} — publishers fail when full (finding C2)"
        - alert: JetStreamConsumerLagging
          expr: gnatsd_jsz_consumer_num_pending{namespace="{{ .Namespace }}"} > 100000
          for: 15m
          labels:
            severity: warning
            vikasa_cluster: {{ .Cluster }}
          annotations:
            summary: "JetStream consumer backlog >100k in cluster {{ .Cluster }} — a sink is falling behind"
        - alert: JetStreamAssetsHigh
          expr: gnatsd_jsz_total_streams{namespace="{{ .Namespace }}"} + gnatsd_jsz_total_consumers{namespace="{{ .Namespace }}"} > 1500
          for: 30m
          labels:
            severity: warning
            vikasa_cluster: {{ .Cluster }}
          annotations:
            summary: "JetStream HA-assets approaching the ~2k/node budget in cluster {{ .Cluster }} — add nodes or partitions"
{{- if not .IsCentral }}
        - alert: NatsLeafDown
          expr: gnatsd_varz_leafnodes{namespace="{{ .Namespace }}"} < 1
          for: 5m
          labels:
            severity: warning
            vikasa_cluster: {{ .Cluster }}
          annotations:
            summary: "Regional cluster {{ .Cluster }} has no leaf uplink to central"
{{- end }}
`))

type prometheusRuleData struct {
	DOT       string
	Cluster   string
	Namespace string
	Release   string
	IsCentral bool
}

// kustomizationTmpl is the per-k8s-cluster Kustomize overlay listing the
// cluster's deployable manifests. Identical across clusters except the central
// cluster, which additionally lists the credhealth PrometheusRule. Tool-agnostic:
// works with `kubectl apply -k` and Argo CD.
var kustomizationTmpl = template.Must(template.New("kustomization").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - streams.yaml
  - certificate.yaml
  - externalsecret.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
{{- if .IsCentral }}
  - credhealth-prometheusrule.yaml
{{- end }}
`))

// credhealthRuleData is prometheusRuleData plus the credhealth exporter's
// metric names, injected from internal/credhealth's exported constants so
// the alert exprs below can never drift from what the exporter actually
// emits (see internal/render's TestCredhealthMetricNamesNoDrift).
type credhealthRuleData struct {
	prometheusRuleData
	MetricCredExpirySeconds  string
	MetricCredHealthLastScan string
}

// credhealthRuleTmpl ships the slip→cliff credential-expiry alerts. Emitted only
// on the central cluster (the issuer is the source of truth for cred expiry); the
// metric source is cmd/credhealth -metrics-out via the node_exporter textfile
// collector. The {{"{{ ... }}"}} actions emit literal Prometheus label templating
// (Go's text/template would otherwise parse the inner braces as its own action).
// exprs are starter thresholds (40d / 5d / expired / 24h-stale) operators tune.
var credhealthRuleTmpl = template.Must(template.New("credhealthrule").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vikasa-credhealth-{{ .Cluster }}
  namespace: {{ .Namespace }}
  labels:
    vikasa.dot: {{ .DOT }}
    vikasa.cluster: {{ .Cluster }}
    release: {{ .Release }}
spec:
  groups:
    - name: vikasa-credhealth-{{ .Cluster }}
      rules:
        - alert: CredExpiringSoon
          expr: {{ .MetricCredExpirySeconds }} < 3456000
          for: 1h
          labels:
            severity: warning
          annotations:
            summary: "Credential {{"{{ $labels.identity }}"}} ({{"{{ $labels.kind }}"}}) expires in under 40 days"
        - alert: CredExpiryCritical
          expr: {{ .MetricCredExpirySeconds }} < 432000
          for: 30m
          labels:
            severity: critical
          annotations:
            summary: "Credential {{"{{ $labels.identity }}"}} ({{"{{ $labels.kind }}"}}) expires in under 5 days"
        - alert: CredExpired
          expr: {{ .MetricCredExpirySeconds }} < 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Credential {{"{{ $labels.identity }}"}} ({{"{{ $labels.kind }}"}}) has EXPIRED"
        - alert: CredHealthStale
          expr: time() - {{ .MetricCredHealthLastScan }} > 86400
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: "credhealth has not reported in over 24h (expiry monitor is blind)"
`))

// leafHost strips a trailing :port from a leaf-endpoint (the host has no other colons).
func leafHost(endpoint string) string {
	if i := strings.LastIndex(endpoint, ":"); i >= 0 {
		return endpoint[:i]
	}
	return endpoint
}

// K8sRenderer renders one cluster's streams as NACK Stream CRs.
type K8sRenderer struct{}

// RenderCluster implements SubstrateRenderer. It emits a single streams.yaml
// containing one NACK Stream CR per stream on this cluster (multi-doc, in the
// order Dispatch already sorted them by name).
func (K8sRenderer) RenderCluster(c ClusterSlice) (map[string][]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(banner)
	for idx, s := range c.Streams {
		if idx > 0 {
			buf.WriteString("---\n")
		}
		doc, err := renderStreamCR(s, c.DOT)
		if err != nil {
			return nil, err
		}
		buf.Write(doc)
	}
	host := leafHost(c.LeafEndpoint)
	dnsNames := []string{host}
	if c.Namespace != "" {
		dnsNames = append(dnsNames, "nats."+c.Namespace+".svc.cluster.local")
	}
	var certBuf bytes.Buffer
	if err := certTmpl.Execute(&certBuf, certData{
		Name:       c.ID + "-nats-server",
		DOT:        c.DOT,
		Cluster:    c.ID,
		SecretName: c.ID + "-nats-server-tls",
		Issuer:     c.IssuerName,
		CommonName: host,
		DNSNames:   dnsNames,
	}); err != nil {
		return nil, fmt.Errorf("k8s render: certificate %s: %w", c.ID, err)
	}

	var esBuf bytes.Buffer
	if err := externalSecretTmpl.Execute(&esBuf, externalSecretData{
		DOT:         c.DOT,
		Cluster:     c.ID,
		SecretStore: c.SecretStore,
		RemoteKey:   "vikasa/" + c.DOT + "/infrahub-token",
	}); err != nil {
		return nil, fmt.Errorf("k8s render: externalsecret %s: %w", c.ID, err)
	}

	var smBuf bytes.Buffer
	if err := serviceMonitorTmpl.Execute(&smBuf, serviceMonitorData{
		DOT: c.DOT, Cluster: c.ID, Namespace: c.Namespace, Release: c.PrometheusRelease,
	}); err != nil {
		return nil, fmt.Errorf("k8s render: servicemonitor %s: %w", c.ID, err)
	}
	var prBuf bytes.Buffer
	if err := prometheusRuleTmpl.Execute(&prBuf, prometheusRuleData{
		DOT: c.DOT, Cluster: c.ID, Namespace: c.Namespace, Release: c.PrometheusRelease, IsCentral: c.IsCentral,
	}); err != nil {
		return nil, fmt.Errorf("k8s render: prometheusrule %s: %w", c.ID, err)
	}

	var ksBuf bytes.Buffer
	if err := kustomizationTmpl.Execute(&ksBuf, prometheusRuleData{
		DOT: c.DOT, Cluster: c.ID, Namespace: c.Namespace, Release: c.PrometheusRelease, IsCentral: c.IsCentral,
	}); err != nil {
		return nil, fmt.Errorf("k8s render: kustomization %s: %w", c.ID, err)
	}

	out := map[string][]byte{
		"streams.yaml":        buf.Bytes(),
		"certificate.yaml":    certBuf.Bytes(),
		"externalsecret.yaml": esBuf.Bytes(),
		"kustomization.yaml":  ksBuf.Bytes(),
		"servicemonitor.yaml": smBuf.Bytes(),
		"prometheusrule.yaml": prBuf.Bytes(),
	}

	if c.IsCentral {
		var chBuf bytes.Buffer
		if err := credhealthRuleTmpl.Execute(&chBuf, credhealthRuleData{
			prometheusRuleData: prometheusRuleData{
				DOT: c.DOT, Cluster: c.ID, Namespace: c.Namespace, Release: c.PrometheusRelease,
			},
			MetricCredExpirySeconds:  credhealth.MetricCredExpirySeconds,
			MetricCredHealthLastScan: credhealth.MetricCredHealthLastScan,
		}); err != nil {
			return nil, fmt.Errorf("k8s render: credhealth-prometheusrule %s: %w", c.ID, err)
		}
		out["credhealth-prometheusrule.yaml"] = chBuf.Bytes()
	}

	return out, nil
}
