package render_test

import (
	"bytes"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/Vikasa2M/vikasa-infra/internal/plan"
	"github.com/Vikasa2M/vikasa-infra/internal/render"
	"github.com/Vikasa2M/vikasa-infra/internal/topology"
)

// loadPlan loads a topology file and builds a Plan, failing the test on error.
func loadPlan(t *testing.T, path string) *plan.Plan {
	t.Helper()
	root, err := topology.Load(path)
	if err != nil {
		t.Fatalf("topology.Load(%q): %v", path, err)
	}
	p, err := plan.Build(root)
	if err != nil {
		t.Fatalf("plan.Build: %v", err)
	}
	return p
}

// goldenPath returns the path to a golden file for the given filename.
func goldenPath(filename string) string {
	return "testdata/golden/" + filename
}

// checkGolden compares got against the committed golden file.
// If the golden file does not exist, the test FAILS with a clear message
// unless the UPDATE_GOLDEN environment variable is set, in which case the
// golden file is written and the test passes (opt-in regeneration).
func checkGolden(t *testing.T, filename string, got []byte) {
	t.Helper()
	path := goldenPath(filename)
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		if os.Getenv("UPDATE_GOLDEN") != "" {
			if werr := os.WriteFile(path, got, 0o644); werr != nil {
				t.Fatalf("write golden %s: %v", path, werr)
			}
			t.Logf("wrote golden file %s (UPDATE_GOLDEN set)", path)
			return
		}
		t.Fatalf("golden file %s does not exist; run with UPDATE_GOLDEN=1 to create it", path)
	}
	if err != nil {
		t.Fatalf("read golden %s: %v", path, err)
	}
	if !bytes.Equal(existing, got) {
		if os.Getenv("UPDATE_GOLDEN") != "" {
			if werr := os.WriteFile(path, got, 0o644); werr != nil {
				t.Fatalf("write golden %s: %v", path, werr)
			}
			t.Logf("updated golden file %s (UPDATE_GOLDEN set)", path)
			return
		}
		t.Errorf("output differs from golden file %s\n--- golden ---\n%s\n--- got ---\n%s",
			path, string(existing), string(got))
	}
}

func TestK8sRenderer_RenderCluster(t *testing.T) {
	p := loadPlan(t, "../../examples/exdot-shared.json")

	var central []plan.Stream
	var regionalD7a []plan.Stream
	for _, s := range p.Streams {
		switch s.Cluster {
		case "core":
			central = append(central, s)
		case "d7a":
			regionalD7a = append(regionalD7a, s)
		}
	}

	centralFiles, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID: "core", SubstrateType: "kubernetes", JSDomain: "core", DOT: p.DOT,
		IsCentral: true, Streams: central,
		LeafEndpoint: "leaf-core.nats.vikasa.exdot:7422", Namespace: "vikasa-core", IssuerName: "vikasa-ca",
		SecretStore: "vikasa-secrets",
	})
	if err != nil {
		t.Fatalf("RenderCluster(core): %v", err)
	}
	centralYAML, ok := centralFiles["streams.yaml"]
	if !ok {
		t.Fatal("core: streams.yaml not produced")
	}
	cs := string(centralYAML)
	if !strings.HasPrefix(cs, "# AUTOGENERATED") {
		t.Errorf("core streams.yaml: missing banner")
	}
	if !strings.Contains(cs, `sync-wave: "0"`) {
		t.Errorf("core streams.yaml: expected sync-wave \"0\"\n%s", cs)
	}
	// Central runs short retention (aggregation/routing, not the archive) and a
	// size bound — findings C1/C2.
	if !strings.Contains(cs, "maxAge: 15m") {
		t.Errorf("core streams.yaml: central must have short maxAge (15m)\n%s", cs)
	}
	if !strings.Contains(cs, "maxBytes:") {
		t.Errorf("core streams.yaml: central must be bounded (maxBytes)\n%s", cs)
	}
	if !strings.Contains(cs, "externalApiPrefix: $JS.d7a.API") || !strings.Contains(cs, "externalApiPrefix: $JS.d7b.API") {
		t.Errorf("core streams.yaml: expected both partition sources\n%s", cs)
	}

	coreCert := string(centralFiles["certificate.yaml"])
	for _, want := range []string{
		"kind: Certificate",
		"name: core-nats-server",
		"name: vikasa-ca",
		"server auth",
		"commonName: leaf-core.nats.vikasa.exdot",
		"- leaf-core.nats.vikasa.exdot",
		"- nats.vikasa-core.svc.cluster.local",
	} {
		if !strings.Contains(coreCert, want) {
			t.Errorf("core certificate.yaml missing %q\n%s", want, coreCert)
		}
	}

	d7aFiles, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID: "d7a", SubstrateType: "kubernetes", JSDomain: "d7a", DOT: p.DOT,
		Streams:      regionalD7a,
		LeafEndpoint: "leaf-d7a.nats.vikasa.exdot:7422", Namespace: "vikasa-d7a", IssuerName: "vikasa-ca",
		SecretStore: "vikasa-secrets",
	})
	if err != nil {
		t.Fatalf("RenderCluster(d7a): %v", err)
	}
	d7aYAML := d7aFiles["streams.yaml"]
	ds := string(d7aYAML)
	if strings.Count(ds, "kind: Stream") != 1 {
		t.Errorf("d7a streams.yaml: expected exactly 1 Stream\n%s", ds)
	}
	if strings.Contains(ds, "sources:") {
		t.Errorf("d7a streams.yaml: regional shell must not have sources\n%s", ds)
	}
	if !strings.Contains(ds, `sync-wave: "1"`) {
		t.Errorf("d7a streams.yaml: expected sync-wave \"1\"\n%s", ds)
	}

	checkGolden(t, "clusters/core/streams.yaml", centralYAML)
	checkGolden(t, "clusters/d7a/streams.yaml", d7aYAML)
}

func TestK8sRenderer_ExternalSecret(t *testing.T) {
	out, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID:            "d7a",
		SubstrateType: "kubernetes",
		Namespace:     "vikasa",
		JSDomain:      "VIKASA_EXDOT_D7_D7A",
		LeafEndpoint:  "nats-d7a.exdot.example:7422",
		DOT:           "exdot",
		IssuerName:    "vikasa-ca",
		SecretStore:   "my-store",
	})
	if err != nil {
		t.Fatalf("RenderCluster: %v", err)
	}
	es, ok := out["externalsecret.yaml"]
	if !ok {
		t.Fatal("externalsecret.yaml not emitted")
	}
	s := string(es)
	for _, want := range []string{
		"kind: ExternalSecret",
		"name: my-store",
		"kind: ClusterSecretStore",
		"name: infrahub-token",
		"secretKey: token",
		"key: vikasa/exdot/infrahub-token",
		"vikasa.cluster: d7a",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("externalsecret.yaml missing %q:\n%s", want, s)
		}
	}
}

func TestK8sRenderer_CertNoNamespace(t *testing.T) {
	files, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID: "core", SubstrateType: "kubernetes", DOT: "exdot",
		LeafEndpoint: "leaf-core.nats.vikasa.exdot:7422", IssuerName: "vikasa-ca",
	})
	if err != nil {
		t.Fatalf("RenderCluster: %v", err)
	}
	cert := string(files["certificate.yaml"])
	if strings.Contains(cert, "svc.cluster.local") {
		t.Errorf("no Namespace set → cert must omit the svc SAN\n%s", cert)
	}
	if !strings.Contains(cert, "- leaf-core.nats.vikasa.exdot") {
		t.Errorf("cert should still have the leaf-endpoint SAN\n%s", cert)
	}
}

func TestK8sRenderer_DMZSourceTransform(t *testing.T) {
	// Build a DMZ stream with two sources that each carry a subject transform
	// (one per share, as required by the validated E1 config).
	dmzStream := plan.Stream{
		Name:     "VIKASA_EXDOT_DMZ",
		Cluster:  "dmz",
		JSDomain: "dmz",
		Replicas: 3,
		Tier:     "dmz",

		Sources: []plan.Source{
			{
				Name:            "VIKASA_EXDOT_CENTRAL",
				Domain:          "core",
				TransformSource: "vikasa.exdot.d1.>",
				TransformDest:   "vikasa.exdot.share.research.>",
			},
			{
				Name:            "VIKASA_EXDOT_CENTRAL",
				Domain:          "core",
				TransformSource: "vikasa.exdot.d1.hwy9.>",
				TransformDest:   "vikasa.peer.exdot.hwy9.>",
			},
		},
	}

	files, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID:            "dmz",
		SubstrateType: "kubernetes",
		DOT:           "exdot",
		JSDomain:      "dmz",
		LeafEndpoint:  "leaf-dmz.nats.vikasa.exdot:7422",
		IssuerName:    "vikasa-ca",
		SecretStore:   "vikasa-secrets",
		Streams:       []plan.Stream{dmzStream},
	})
	if err != nil {
		t.Fatalf("RenderCluster(dmz): %v", err)
	}
	streamsYAML, ok := files["streams.yaml"]
	if !ok {
		t.Fatal("dmz: streams.yaml not produced")
	}
	s := string(streamsYAML)

	// Source name must be the real central stream, not a synthetic per-share name.
	if strings.Count(s, "name: VIKASA_EXDOT_CENTRAL") != 2 {
		t.Errorf("expected exactly 2 sources named VIKASA_EXDOT_CENTRAL:\n%s", s)
	}
	// Both externalApiPrefix entries must point to $JS.core.API.
	if strings.Count(s, "externalApiPrefix: $JS.core.API") != 2 {
		t.Errorf("expected exactly 2 externalApiPrefix: $JS.core.API:\n%s", s)
	}
	// subjectTransforms blocks must be present, not filterSubject.
	if !strings.Contains(s, "subjectTransforms:") {
		t.Errorf("expected subjectTransforms: block:\n%s", s)
	}
	if strings.Contains(s, "filterSubject:") {
		t.Errorf("DMZ sources must not emit filterSubject (transforms used instead):\n%s", s)
	}
	// Verify the two transform pairs.
	for _, want := range []string{
		"source: vikasa.exdot.d1.>",
		"dest: vikasa.exdot.share.research.>",
		"source: vikasa.exdot.d1.hwy9.>",
		"dest: vikasa.peer.exdot.hwy9.>",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("streams.yaml missing %q:\n%s", want, s)
		}
	}
}

func TestK8sRenderer_JetStreamAlerts(t *testing.T) {
	files, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID: "d7a", SubstrateType: "kubernetes", DOT: "exdot", JSDomain: "d7a", Namespace: "vikasa-d7a",
		LeafEndpoint: "leaf-d7a.nats.vikasa.exdot:7422", IssuerName: "vikasa-ca", SecretStore: "vikasa-secrets",
		PrometheusRelease: "kube-prometheus-stack",
	})
	if err != nil {
		t.Fatalf("RenderCluster: %v", err)
	}
	pr := string(files["prometheusrule.yaml"])
	for _, want := range []string{"JetStreamStorageHigh", "JetStreamConsumerLagging", "JetStreamAssetsHigh", "gnatsd_jsz_"} {
		if !strings.Contains(pr, want) {
			t.Errorf("prometheusrule.yaml missing %q:\n%s", want, pr)
		}
	}
}

func TestK8sRenderer_RePublish(t *testing.T) {
	dmz := plan.Stream{
		Name: "VIKASA_EXDOT_DMZ", Cluster: "dmz", JSDomain: "dmz", Replicas: 3, Tier: "dmz",
		MaxAge: "1h", MaxBytes: 10 << 30, Duplicates: "5m",
		RePublishSource: "vikasa.>", RePublishDest: "vikasa.>",
	}
	files, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID: "dmz", SubstrateType: "kubernetes", DOT: "exdot", JSDomain: "dmz",
		LeafEndpoint: "leaf-dmz.nats.vikasa.exdot:7422", IssuerName: "vikasa-ca", SecretStore: "vikasa-secrets",
		Streams: []plan.Stream{dmz},
	})
	if err != nil {
		t.Fatalf("RenderCluster: %v", err)
	}
	s := string(files["streams.yaml"])
	for _, want := range []string{"republish:", "source: vikasa.>", "destination: vikasa.>"} {
		if !strings.Contains(s, want) {
			t.Errorf("CR missing %q:\n%s", want, s)
		}
	}
}

func TestK8sRenderer_StreamBounds(t *testing.T) {
	dmz := plan.Stream{
		Name: "VIKASA_EXDOT_DMZ", Cluster: "dmz", JSDomain: "dmz", Replicas: 3, Tier: "dmz",
		MaxAge: "1h", MaxBytes: 10 << 30, Duplicates: "5m",
	}
	reg := plan.Stream{
		Name: "VIKASA_EXDOT_D7_D7_0", Cluster: "dmz", JSDomain: "dmz", Replicas: 3, Tier: "regional",
		MaxAge: "6h", MaxBytes: 50 << 30,
	}
	files, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID: "dmz", SubstrateType: "kubernetes", DOT: "exdot", JSDomain: "dmz",
		LeafEndpoint: "leaf-dmz.nats.vikasa.exdot:7422", IssuerName: "vikasa-ca", SecretStore: "vikasa-secrets",
		Streams: []plan.Stream{dmz, reg},
	})
	if err != nil {
		t.Fatalf("RenderCluster: %v", err)
	}
	s := string(files["streams.yaml"])
	for _, want := range []string{
		"maxBytes: 10737418240", // dmz 10 GiB
		"duplicateWindow: 5m",   // dmz dedup window
		"maxBytes: 53687091200", // regional 50 GiB
		"maxAge: 1h",
		"maxAge: 6h",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("streams.yaml missing %q:\n%s", want, s)
		}
	}
	// Only the DMZ stream carries a dedup window.
	if strings.Count(s, "duplicateWindow:") != 1 {
		t.Errorf("expected exactly 1 duplicateWindow (dmz only):\n%s", s)
	}
}

func TestK8sRenderer_Kustomization(t *testing.T) {
	out, err := render.K8sRenderer{}.RenderCluster(render.ClusterSlice{
		ID: "d7a", SubstrateType: "kubernetes", Namespace: "vikasa",
		JSDomain: "VIKASA_EXDOT_D7_D7A", LeafEndpoint: "nats-d7a.exdot.example:7422",
		DOT: "exdot", IssuerName: "vikasa-ca", SecretStore: "vikasa-secrets",
	})
	if err != nil {
		t.Fatalf("RenderCluster: %v", err)
	}
	k, ok := out["kustomization.yaml"]
	if !ok {
		t.Fatal("kustomization.yaml not emitted")
	}
	s := string(k)
	for _, want := range []string{"kind: Kustomization", "- streams.yaml", "- certificate.yaml", "- externalsecret.yaml"} {
		if !strings.Contains(s, want) {
			t.Errorf("kustomization.yaml missing %q:\n%s", want, s)
		}
	}
}
