package render

import (
	"bytes"
	"fmt"
	"sort"
	"text/template"

	"github.com/Vikasa2M/vikasa-infra/internal/plan"
	"github.com/Vikasa2M/vikasa-infra/internal/topology"
)

// Output is the packaging mode for kubernetes cluster slices.
type Output string

const (
	OutputKustomize Output = "kustomize" // clusters/<id>/ overlays (default; "" means kustomize)
	OutputHelm      Output = "helm"      // charts/<id>/ Helm charts
)

// Config carries renderer-wide deployment knobs (flags from cmd/gen).
type Config struct {
	TLSIssuer          string // cert-manager (Cluster)Issuer (B3)
	SecretStore        string // External Secrets (Cluster)SecretStore (B5)
	ArgoRepoURL        string // git repo for the Argo Application source; "" disables Application emission
	ArgoTargetRevision string // Argo Application targetRevision (e.g. "main")
	PrometheusRelease  string // Prometheus Operator release label on generated ServiceMonitor/PrometheusRule CRs
	Output             Output // packaging mode: OutputKustomize (default) | OutputHelm
}

// SliceDir is the output subdirectory for a cluster's slice: charts/<id>/ for a
// kubernetes cluster in Helm mode, else clusters/<id>/. It is the single owner
// of the packaging-path decision (Dispatch and the runbook use it; the
// Argo-application path builds its own no-slash form).
func SliceDir(clusterID string, isK8s bool, out Output) string {
	if isK8s && out == OutputHelm {
		return "charts/" + clusterID + "/"
	}
	return "clusters/" + clusterID + "/"
}

// ClusterSlice is everything a substrate renderer needs to materialize one
// cluster's portion of a Plan. The Plan stays substrate-free; Dispatch is the
// only place that reads topology substrate detail and assembles these slices.
type ClusterSlice struct {
	ID                  string
	SubstrateType       string // topology.SubstrateType label ("kubernetes" | "bare-metal")
	Hosts               []string
	Namespace           string
	JSDomain            string
	LeafEndpoint        string
	Streams             []plan.Stream
	IsCentral           bool
	CentralLeafEndpoint string // central cluster's leaf-endpoint; "" when IsCentral
	DOT                 string
	IssuerName          string
	SecretStore         string
	PrometheusRelease   string
}

// SubstrateRenderer renders one cluster's slice into filename->bytes, where the
// filenames are RELATIVE to that cluster's output directory.
type SubstrateRenderer interface {
	RenderCluster(c ClusterSlice) (map[string][]byte, error)
}

// argoAppTmpl renders an Argo CD Application (per-cluster pull) whose source is the
// cluster's clusters/<id> path. Emitted by Dispatch when -argo-repo-url is set.
// destination.server is hardcoded to in-cluster (https://kubernetes.default.svc);
// a future hub/ApplicationSet profile (C4) would make the destination per-cluster.
var argoAppTmpl = template.Must(template.New("argoapp").Parse(`# AUTOGENERATED by vikasa-infra/cmd/gen
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Name }}
  namespace: argocd
  labels:
    vikasa.dot: {{ .DOT }}
    vikasa.cluster: {{ .Cluster }}
spec:
  project: default
  source:
    repoURL: {{ .RepoURL }}
    targetRevision: {{ .TargetRevision }}
    path: {{ .Path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
`))

type argoAppData struct {
	Name           string
	DOT            string
	Cluster        string
	RepoURL        string
	TargetRevision string
	Path           string
	Namespace      string
}

// Dispatch groups the plan's streams by placement cluster, assembles a
// ClusterSlice per cluster from the topology, routes each to the renderer
// matching its substrate, and returns filename->bytes with each cluster's files
// prefixed by clusters/<id>/ (or charts/<id>/ for kubernetes clusters when
// cfg.Output is "helm").
func Dispatch(p *plan.Plan, root *topology.Root, cfg Config) (map[string][]byte, error) {
	if root == nil || root.Topology == nil {
		return nil, fmt.Errorf("dispatch: nil topology")
	}
	t := root.Topology

	centralID := ""
	if t.Central != nil && t.Central.Cluster != nil {
		centralID = *t.Central.Cluster
	}
	centralLeafEndpoint := ""
	if c, ok := t.Cluster[centralID]; ok && c != nil && c.LeafEndpoint != nil {
		centralLeafEndpoint = *c.LeafEndpoint
	}

	byCluster := map[string][]plan.Stream{}
	for _, s := range p.Streams {
		byCluster[s.Cluster] = append(byCluster[s.Cluster], s)
	}

	ids := make([]string, 0, len(byCluster))
	for id := range byCluster {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	out := map[string][]byte{}
	for _, id := range ids {
		c, ok := t.Cluster[id]
		if !ok || c == nil {
			return nil, fmt.Errorf("dispatch: cluster %q referenced by a stream is not in the topology", id)
		}
		slice, err := buildClusterSlice(p, c, id, centralID, centralLeafEndpoint, byCluster[id])
		if err != nil {
			return nil, err
		}
		slice.IssuerName = cfg.TLSIssuer
		slice.SecretStore = cfg.SecretStore
		slice.PrometheusRelease = cfg.PrometheusRelease

		var r SubstrateRenderer
		switch slice.SubstrateType {
		case topology.SubstrateKubernetes.String():
			r = K8sRenderer{}
		case topology.SubstrateBareMetal.String():
			r = BareMetalRenderer{}
		default:
			return nil, fmt.Errorf("dispatch: cluster %q has unsupported substrate %q", id, slice.SubstrateType)
		}

		dir := SliceDir(id, slice.SubstrateType == topology.SubstrateKubernetes.String(), cfg.Output)
		if slice.SubstrateType == topology.SubstrateKubernetes.String() && cfg.Output == OutputHelm {
			chartFiles, err := renderHelmChart(slice)
			if err != nil {
				return nil, err
			}
			for name, content := range chartFiles {
				out[dir+name] = content
			}
		} else {
			files, err := r.RenderCluster(slice)
			if err != nil {
				return nil, err
			}
			for name, content := range files {
				out[dir+name] = content
			}
		}

		if slice.SubstrateType == topology.SubstrateKubernetes.String() && cfg.ArgoRepoURL != "" {
			argoPath := "clusters/" + id
			if cfg.Output == OutputHelm {
				argoPath = "charts/" + id
			}
			var appBuf bytes.Buffer
			if err := argoAppTmpl.Execute(&appBuf, argoAppData{
				Name:           "vikasa-" + id,
				DOT:            slice.DOT,
				Cluster:        id,
				RepoURL:        cfg.ArgoRepoURL,
				TargetRevision: cfg.ArgoTargetRevision,
				Path:           argoPath,
				Namespace:      slice.Namespace,
			}); err != nil {
				return nil, fmt.Errorf("dispatch: argo application %s: %w", id, err)
			}
			out["argocd/"+id+".yaml"] = appBuf.Bytes()
		}
	}
	return out, nil
}

func buildClusterSlice(p *plan.Plan, c *topology.Cluster, id, centralID, centralLeafEndpoint string, streams []plan.Stream) (ClusterSlice, error) {
	if c.Substrate == nil {
		return ClusterSlice{}, fmt.Errorf("dispatch: cluster %q has no substrate", id)
	}
	var subType string
	switch c.Substrate.Type {
	case topology.SubstrateKubernetes:
		subType = topology.SubstrateKubernetes.String()
	case topology.SubstrateBareMetal:
		subType = topology.SubstrateBareMetal.String()
	default:
		return ClusterSlice{}, fmt.Errorf("dispatch: cluster %q has unset/unknown substrate type", id)
	}

	jsDomain := ""
	if c.JsDomain != nil {
		jsDomain = *c.JsDomain
	}
	leafEP := ""
	if c.LeafEndpoint != nil {
		leafEP = *c.LeafEndpoint
	}
	ns := ""
	if c.Substrate.Namespace != nil {
		ns = *c.Substrate.Namespace
	}
	hosts := append([]string(nil), c.Substrate.Hosts...)
	sort.Strings(hosts)

	sort.Slice(streams, func(i, j int) bool { return streams[i].Name < streams[j].Name })

	isCentral := id == centralID
	cle := centralLeafEndpoint
	if isCentral {
		cle = ""
	}

	return ClusterSlice{
		ID:                  id,
		SubstrateType:       subType,
		Hosts:               hosts,
		Namespace:           ns,
		JSDomain:            jsDomain,
		LeafEndpoint:        leafEP,
		Streams:             streams,
		IsCentral:           isCentral,
		CentralLeafEndpoint: cle,
		DOT:                 p.DOT,
	}, nil
}
